// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: service_tinybank.proto

package pb

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_service_tinybank_proto protoreflect.FileDescriptor

const file_service_tinybank_proto_rawDesc = "" +
	"\n" +
	"\x16service_tinybank.proto\x12\x02pb\x1a\x1cgoogle/api/annotations.proto\x1a\x15rpc_create_user.proto\x1a\x15rpc_update_user.proto\x1a\x14rpc_login_user.proto\x1a\x16rpc_verify_email.proto\x1a\x12rpc_get_user.proto\x1a.protoc-gen-openapiv2/options/annotations.proto2\xcf\x05\n" +
	"\bTinyBank\x12\x8e\x01\n" +
	"\n" +
	"CreateUser\x12\x15.pb.CreateUserRequest\x1a\x16.pb.CreateUserResponse\"Q\x92A4\x12\x0fCreate new user\x1a!Use this API to create a new user\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/create_user\x12\x84\x01\n" +
	"\n" +
	"UpdateUser\x12\x15.pb.UpdateUserRequest\x1a\x16.pb.UpdateUserResponse\"G\x92A*\x12\vUpdate user\x1a\x1bUse this API to update user\x82\xd3\xe4\x93\x02\x14:\x01*2\x0f/v1/update_user\x12\xa3\x01\n" +
	"\tLoginUser\x12\x14.pb.LoginUserRequest\x1a\x15.pb.LoginUserResponse\"i\x92AM\x12\n" +
	"Login user\x1a?Use this API to login user and get access token & refresh token\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/login_user\x12\x96\x01\n" +
	"\vVerifyEmail\x12\x16.pb.VerifyEmailRequest\x1a\x17.pb.VerifyEmailResponse\"V\x92A;\x12\fVerify email\x1a+Use this API to verify user's email address\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/verify-email\x12l\n" +
	"\aGetUser\x12\x12.pb.GetUserRequest\x1a\x13.pb.GetUserResponse\"8\x92A$\x12\bGet user\x1a\x18Use this API to get user\x82\xd3\xe4\x93\x02\v\x12\t/v1/usersB\x97\x01\x92AY\x12W\n" +
	"\fTinybank API\"B\n" +
	"\x03NVD\x12 https://github.com/dungNguyen203\x1a\x19dungnguyennvd11@gmail.com2\x031.2Z9github.com/dungNguyen203/grpc-go-product-service/proto/pbb\x06proto3"

var file_service_tinybank_proto_goTypes = []any{
	(*CreateUserRequest)(nil),   // 0: pb.CreateUserRequest
	(*UpdateUserRequest)(nil),   // 1: pb.UpdateUserRequest
	(*LoginUserRequest)(nil),    // 2: pb.LoginUserRequest
	(*VerifyEmailRequest)(nil),  // 3: pb.VerifyEmailRequest
	(*GetUserRequest)(nil),      // 4: pb.GetUserRequest
	(*CreateUserResponse)(nil),  // 5: pb.CreateUserResponse
	(*UpdateUserResponse)(nil),  // 6: pb.UpdateUserResponse
	(*LoginUserResponse)(nil),   // 7: pb.LoginUserResponse
	(*VerifyEmailResponse)(nil), // 8: pb.VerifyEmailResponse
	(*GetUserResponse)(nil),     // 9: pb.GetUserResponse
}
var file_service_tinybank_proto_depIdxs = []int32{
	0, // 0: pb.TinyBank.CreateUser:input_type -> pb.CreateUserRequest
	1, // 1: pb.TinyBank.UpdateUser:input_type -> pb.UpdateUserRequest
	2, // 2: pb.TinyBank.LoginUser:input_type -> pb.LoginUserRequest
	3, // 3: pb.TinyBank.VerifyEmail:input_type -> pb.VerifyEmailRequest
	4, // 4: pb.TinyBank.GetUser:input_type -> pb.GetUserRequest
	5, // 5: pb.TinyBank.CreateUser:output_type -> pb.CreateUserResponse
	6, // 6: pb.TinyBank.UpdateUser:output_type -> pb.UpdateUserResponse
	7, // 7: pb.TinyBank.LoginUser:output_type -> pb.LoginUserResponse
	8, // 8: pb.TinyBank.VerifyEmail:output_type -> pb.VerifyEmailResponse
	9, // 9: pb.TinyBank.GetUser:output_type -> pb.GetUserResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_tinybank_proto_init() }
func file_service_tinybank_proto_init() {
	if File_service_tinybank_proto != nil {
		return
	}
	file_rpc_create_user_proto_init()
	file_rpc_update_user_proto_init()
	file_rpc_login_user_proto_init()
	file_rpc_verify_email_proto_init()
	file_rpc_get_user_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_tinybank_proto_rawDesc), len(file_service_tinybank_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_tinybank_proto_goTypes,
		DependencyIndexes: file_service_tinybank_proto_depIdxs,
	}.Build()
	File_service_tinybank_proto = out.File
	file_service_tinybank_proto_goTypes = nil
	file_service_tinybank_proto_depIdxs = nil
}
